<?php
/**
* Plugin Name: Connect to WebApp Plugin
* Plugin URI: 
* Description:   This plugin connects a WordPress website to the web app to request a verification code and perform registration.
* Version:          
* Author:  Elham Bidarigh          
* Author URI: elham.bidarigh@gmail.com
*/
 

 
 function loginFromApp(){
 
  if(!isset($_SESSION["keshenauth"]) || $_SESSION["keshenauth"] == "Not"){  

 
$vall = "";
$vall .= '<style>form#getPhoneNumber,#checkPhoneNumber {';
$vall .= 'width: 90%;';
$vall .= 'margin: 0 auto;';
$vall .= 'text-align: center;';
$vall .= 'border: 1px solid #7b013c;';
$vall .= 'padding: 20px 10px;';
$vall .= 'border-radius: 5px;';
$vall .= 'background: #fdfdfd;';
$vall .= '}input#phoneNumber ,#codeNumber{';
$vall .= 'direction: ltr;';
$vall .= 'text-align: center;';
$vall .= 'color: #000;';
$vall .= 'font-size: 17px;';
$vall .= 'letter-spacing: 5px;';
$vall .= 'font-weight: 700;';
$vall .= 'border: 1px solid #7b013c;';
$vall .= 'margin: 20px auto;';
$vall .= '}label.loginlabel {';
$vall .= 'font-size: 17px;';
$vall .= 'font-weight: 700;';
$vall .= '}#sendPhone ,#checkCode{';
$vall .= 'color: #fff;';
$vall .= 'background: #7b013c;';
$vall .= 'font-weight: 700;';
$vall .= 'font-size: 21px;';
$vall .= 'padding: 12px 40px;cursor: pointer;';
$vall .= 'border-radius: 5px;';
$vall .= 'display: block;';
$vall .= 'line-height: 1;';
$vall .= '}#checkPhoneNumber{';
$vall .= 'display:none;}';
$vall .= '.successLogin{';
$vall .= 'text-align: center;';
$vall .= 'display: none;';
$vall .= 'background: #7b013c;';
$vall .= 'width: 90%;';
$vall .= 'margin: 10px auto;';
$vall .= 'border-radius: 6px;';
$vall .= 'padding: 30px;';
$vall .= 'color: #FFF;';
$vall .= 'font-size: 19px;';
$vall .= '}';
$vall .= '.successLogin a {';
$vall .= 'background: #FFF;';
$vall .= 'padding: 7px 15px;';
$vall .= 'border-radius: 5px;';
$vall .= 'margin: 10px auto;';
$vall .= 'display: inline-block;';
$vall .= 'font-size: 18px;';
$vall .= 'font-weight: 700;';
$vall .= '}svg.svg-inline--fa.fa-check-circle.fa-w-16 {';
$vall .= 'width: 100px;';
$vall .= '}';
$vall .= '#loginPopup {';
$vall .= 'position: fixed;';
$vall .= 'left: 50%;';
$vall .= 'right: auto;';
$vall .= 'top: 50%;';
$vall .= 'background: #e7e7e7;';
$vall .= 'width: 90%;';
$vall .= 'max-width: 500px;';
$vall .= 'transform: translate(-50%, -50%);';
$vall .= 'padding: 50px 0;';
$vall .= 'border-radius: 6px;';
$vall .= 'box-shadow: 0 0 5px;';
$vall .= 'display:none;z-index: 999999999;';
$vall .= '}';
$vall .= '#errorr {';
$vall .= 'color: red;';
$vall .= 'display: none;';
$vall .= 'font-size: 13px;';
$vall .= '}';
$vall .= 'svg#closeMypopUps {cursor: pointer;';
$vall .= 'width: 17px;';
$vall .= 'height: 17px;';
$vall .= 'float: left;';
$vall .= 'margin-left: 10px;';
$vall .= 'margin-top: -35px;';
$vall .= 'color: #7b013c;';
$vall .= '}';
$vall .= '</style>';
//$vall .= '<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>';
$vall .= '<script>';
$vall .= '$(document).keypress(';
$vall .= 'function(event){';
$vall .= 'if (event.which == "13") {';
$vall .= 'event.preventDefault();';
$vall .= '}';
$vall .= '});';
$vall .= '';
$vall .= '$(document).ready(function(){';
$vall .= '';
$vall .= '$(document).on("click","#MyaccountLinkLogo",function(e) {';
$vall .= '';
$vall .= 'e.preventDefault();';
$vall .= '$("#loginPopup").show();';
$vall .= '});';
$vall .= '';
$vall .= '';
$vall .= '$("#closeMypopUps").on("click",function(e){';
$vall .= 'e.preventDefault();';
$vall .= '$("#loginPopup").hide();';
$vall .= '});';
$vall .= '$("#sendPhone").on("click",function(e){';
$vall .= 'e.preventDefault();';
$vall .= 'var phones = $("#phoneNumber").val();';
$vall .= '';
$vall .= 'function toEnglishNumber(strNum) {';
$vall .= 'var pn = ["۰", "۱", "۲", "۳", "۴", "۵", "۶", "۷", "۸", "۹"];';
$vall .= 'var en = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"];';
$vall .= 'var an = ["٠", "١", "٢", "٣", "٤", "٥", "٦", "٧", "٨", "٩"];';
$vall .= 'var cache = strNum;';
$vall .= 'for (var i = 0; i < 10; i++) {';
$vall .= 'var regex_fa = new RegExp(pn[i], "g");';
$vall .= 'var regex_ar = new RegExp(an[i], "g");';
$vall .= 'cache = cache.replace(regex_fa, en[i]);';
$vall .= 'cache = cache.replace(regex_ar, en[i]);';
$vall .= '}';
$vall .= 'return cache;';
$vall .= '}';
$vall .= '';
$vall .= 'phones = toEnglishNumber(phones);';
$vall .= '';
$vall .= 'if(phones[0] !== "0"){';
$vall .= 'phones ="0" + phones;';
$vall .= '}';
$vall .= '';
$vall .= 'if(phones != ""){';
$vall .= 'jQuery.ajax({';
$vall .= 'type: "post",';
$vall .= 'dataType: "json",';
$vall .= 'data : {phone:phones},';
$vall .= 'url: "'.esc_attr( get_option('myapiurl') ).'/user/login/phone",';
$vall .= 'success: function(data){';
$vall .= 'if(data.success == true){';
$vall .= '$("#checkPhoneNumber").fadeIn();';
$vall .= '$("#getPhoneNumber").fadeOut();';
$vall .= '}';
$vall .= '';
$vall .= '}';
$vall .= '});';
 
$vall .= '}';
$vall .= '});';
$vall .= '';
$vall .= '';
$vall .= '';
$vall .= '$("#checkCode").on("click",function(e){';
$vall .= 'e.preventDefault();';
$vall .= 'function toEnglishNumber(strNum) {';
$vall .= 'var pn = ["۰", "۱", "۲", "۳", "۴", "۵", "۶", "۷", "۸", "۹"];';
$vall .= 'var en = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"];';
$vall .= 'var an = ["٠", "١", "٢", "٣", "٤", "٥", "٦", "٧", "٨", "٩"];';
$vall .= 'var cache = strNum;';
$vall .= 'for (var i = 0; i < 10; i++) {';
$vall .= 'var regex_fa = new RegExp(pn[i], "g");';
$vall .= 'var regex_ar = new RegExp(an[i], "g");';
$vall .= 'cache = cache.replace(regex_fa, en[i]);';
$vall .= 'cache = cache.replace(regex_ar, en[i]);';
$vall .= '}';
$vall .= 'return cache;';
$vall .= '}';
$vall .= 'var phones =  toEnglishNumber($("#phoneNumber").val());';
$vall .= 'var code = toEnglishNumber($("#codeNumber").val());';
$vall .= '$("#codeNumber").val("");';
$vall .= 'if(code != ""){';
$vall .= 'jQuery.ajax({';
$vall .= 'type: "post",';
$vall .= 'dataType: "json",';
$vall .= 'data : {phone:phones,verify_code:code},';
$vall .= 'url: "'.esc_attr( get_option('myapiurl') ).'/user/verify/phone",';
$vall .= 'success: function(data){';
$vall .= 'if(data.success == true){';
$vall .= '$("#checkPhoneNumber").fadeOut();';
$vall .= '$(".successLogin").fadeIn();';
$vall .= 'jQuery.ajax({';
$vall .= 'type: "get",';
$vall .= 'dataType: "json",';
$vall .= 'data : {token:data.data.token},';
$vall .= 'url: "https://avayar.app/wp-content/themes/woodmart/loginpage.php",';
$vall .= 'success: function(data){ } });';
$vall .= 'location.reload();';
$vall .= '$("#MyaccountLinkLogo").attr("href","/user-account").attr("id","MyaccountLinks");';
$vall .= '';
$vall .= '}';
$vall .= '';
$vall .= '';
$vall .= '';
$vall .= '} ,error: function () {';
$vall .= '$("#errorr").show();';
$vall .= '}';
$vall .= '});';
$vall .= '';
$vall .= '';
$vall .= '}';
$vall .= '});';
$vall .= '';
$vall .= '';
$vall .= '});';
$vall .= '</script>';
$vall .= '<div id="loginPopup">';
$vall .= '<svg aria-hidden="true" focusable="false" id="closeMypopUps" data-prefix="fas" data-icon="times" class="svg-inline--fa fa-times fa-w-11" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 352 512"><path fill="currentColor" d="M242.72 256l100.07-100.07c12.28-12.28 12.28-32.19 0-44.48l-22.24-22.24c-12.28-12.28-32.19-12.28-44.48 0L176 189.28 75.93 89.21c-12.28-12.28-32.19-12.28-44.48 0L9.21 111.45c-12.28 12.28-12.28 32.19 0 44.48L109.28 256 9.21 356.07c-12.28 12.28-12.28 32.19 0 44.48l22.24 22.24c12.28 12.28 32.2 12.28 44.48 0L176 322.72l100.07 100.07c12.28 12.28 32.2 12.28 44.48 0l22.24-22.24c12.28-12.28 12.28-32.19 0-44.48L242.72 256z"></path></svg>';
$vall .= '<form class="applginform" id="getPhoneNumber">';
$vall .= '<label for="phoneNumber" class="loginlabel">شماره همراه خود را وارد نمایید</label>';
$vall .= '<input type="text" placeholder=""  value="0" style="direction:ltr" name="phone" id="phoneNumber"  class="loginphone"/>';
$vall .= '<span id="sendPhone">ثبت</span>';
$vall .= '</form>';
$vall .= '';
$vall .= '';
$vall .= '<form class="applginform" id="checkPhoneNumber" >';
$vall .= '';
$vall .= '<label for="codeNumber" class="loginlabel">رمز یکبار مصرف ارسال شده را وارد نمایید</label>';
$vall .= '<span   id="errorr">کد وارد شده صحیح نمی باشد</span>';
$vall .= '<input type="text" placeholder="" name="code" id="codeNumber"  class="loginphone"/>';
$vall .= '<span id="checkCode">ثبت</span>';
$vall .= '</form>';
$vall .= '';
$vall .= '<div class="successLogin">';
$vall .= '<svg aria-hidden="true" focusable="false" data-prefix="far" data-icon="check-circle" class="svg-inline--fa fa-check-circle fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M256 8C119.033 8 8 119.033 8 256s111.033 248 248 248 248-111.033 248-248S392.967 8 256 8zm0 48c110.532 0 200 89.451 200 200 0 110.532-89.451 200-200 200-110.532 0-200-89.451-200-200 0-110.532 89.451-200 200-200m140.204 130.267l-22.536-22.718c-4.667-4.705-12.265-4.736-16.97-.068L215.346 303.697l-59.792-60.277c-4.667-4.705-12.265-4.736-16.97-.069l-22.719 22.536c-4.705 4.667-4.736 12.265-.068 16.971l90.781 91.516c4.667 4.705 12.265 4.736 16.97.068l172.589-171.204c4.704-4.668 4.734-12.266.067-16.971z"></path></svg>';
$vall .= '<div>تبریک . شما با موفقیت وارد سامانه شدید </div>';
$vall .= '<a href="https://avayar.app/user-account/">ناحیه کاربری</a>';
$vall .= '';
$vall .= '</div>';
$vall .= '</div>';
$vall .= '';
return $vall;

 }
  
}
 
 add_shortcode( 'loginForm' , 'loginFromApp' );
 




 function accountFrm(){
 if(!isset($_SESSION["keshenauth"]) || $_SESSION["keshenauth"] == "Not"){ 
	 $vall = '';
$vall .= '<style>form#getPhoneNumber2,#checkPhoneNumber2 {';
$vall .= 'width: 90%;';
$vall .= 'margin: 0 auto;';
$vall .= 'text-align: center;';
$vall .= 'border: 1px solid #7b013c;';
$vall .= 'padding: 20px 10px;';
$vall .= 'border-radius: 5px;';
$vall .= 'background: #fdfdfd;';
$vall .= '}input#phoneNumber2 ,#codeNumber2{';
$vall .= 'direction: ltr;';
$vall .= 'text-align: center;';
$vall .= 'color: #000;';
$vall .= 'font-size: 17px;';
$vall .= 'letter-spacing: 5px;';
$vall .= 'font-weight: 700;';
$vall .= 'border: 1px solid #7b013c;';
$vall .= 'margin: 20px auto;';
$vall .= '}label.loginlabel {';
$vall .= 'font-size: 17px;';
$vall .= 'font-weight: 700;';
$vall .= '}#sendPhone2 ,#checkCode2{';
$vall .= 'color: #fff;';
$vall .= 'background: #7b013c;';
$vall .= 'font-weight: 700;';
$vall .= 'font-size: 21px;';
$vall .= 'padding: 12px 40px;cursor: pointer;';
$vall .= 'border-radius: 5px;';
$vall .= 'display: block;';
$vall .= 'line-height: 1;';
$vall .= '}#checkPhoneNumber2{';
$vall .= 'display:none;}';
$vall .= '.successLogin{';
$vall .= 'text-align: center;';
$vall .= 'display: none;';
$vall .= 'background: #7b013c;';
$vall .= 'width: 90%;';
$vall .= 'margin: 10px auto;';
$vall .= 'border-radius: 6px;';
$vall .= 'padding: 30px;';
$vall .= 'color: #FFF;';
$vall .= 'font-size: 19px;';
$vall .= '} .successLogin2{';
$vall .= 'text-align: center;';
$vall .= '';
$vall .= 'background: #7b013c;';
$vall .= 'width: 90%;';
$vall .= 'margin: 10px auto;';
$vall .= 'border-radius: 6px;';
$vall .= 'padding: 30px;';
$vall .= 'color: #FFF;';
$vall .= 'font-size: 19px;';
$vall .= '}    	#errorr {';
$vall .= 'color: red;';
$vall .= 'display: none;';
$vall .= 'font-size: 13px;';
$vall .= '}';
$vall .= '.successLogin a ,.successLogin2 a{';
$vall .= 'background: #FFF;';
$vall .= 'padding: 7px 15px;';
$vall .= 'border-radius: 5px;';
$vall .= 'margin: 10px auto;';
$vall .= 'display: inline-block;';
$vall .= 'font-size: 18px;';
$vall .= 'font-weight: 700;';
$vall .= '}svg.svg-inline--fa.fa-check-circle.fa-w-16 {';
$vall .= 'width: 100px;';
$vall .= '}';
$vall .= 'svg.svg-inline--fa.fa-user-circle.fa-w-16 {';
$vall .= 'width: 170px;';
$vall .= '}';
$vall .= '';
$vall .= '</style>';
//$vall .= '<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>';
$vall .= '<script>';
$vall .= '$(document).keypress(';
$vall .= 'function(event){';
$vall .= 'if (event.which == "13") {';
$vall .= 'event.preventDefault();';
$vall .= '}';
$vall .= '});';
$vall .= '';
$vall .= '$(document).ready(function(){';
$vall .= '';
$vall .= '';
$vall .= '';
$vall .= '$("#sendPhone2").on("click",function(e){';
$vall .= '';
$vall .= 'function toEnglishNumber(strNum) {';
$vall .= 'var pn = ["۰", "۱", "۲", "۳", "۴", "۵", "۶", "۷", "۸", "۹"];';
$vall .= 'var en = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"];';
$vall .= 'var an = ["٠", "١", "٢", "٣", "٤", "٥", "٦", "٧", "٨", "٩"];';
$vall .= 'var cache = strNum;';
$vall .= 'for (var i = 0; i < 10; i++) {';
$vall .= 'var regex_fa = new RegExp(pn[i], "g");';
$vall .= 'var regex_ar = new RegExp(an[i], "g");';
$vall .= 'cache = cache.replace(regex_fa, en[i]);';
$vall .= 'cache = cache.replace(regex_ar, en[i]);';
$vall .= '}';
$vall .= 'return cache;';
$vall .= '}';
$vall .= '';
$vall .= 'e.preventDefault();';
$vall .= 'var phones =  toEnglishNumber($("#phoneNumber2").val());';
$vall .= '';
$vall .= 'if(phones[0] !== "0"){';
$vall .= 'phones ="0" + phones;';
$vall .= '}';
$vall .= 'if(phones != ""){';
$vall .= 'jQuery.ajax({';
$vall .= 'type: "post",'; 
$vall .= 'dataType: "json",';
$vall .= 'data : {phone:phones},';
$vall .= 'url: "'.esc_attr( get_option('myapiurl') ).'/user/login/phone",';
$vall .= 'success: function(data){';
$vall .= 'if(data.success == true){';
$vall .= '$("#checkPhoneNumber2").fadeIn();';
$vall .= '$("#getPhoneNumber2").fadeOut();';
$vall .= '}';
$vall .= '';
$vall .= '}';
$vall .= '});';
$vall .= '';
$vall .= '';
$vall .= '}';
$vall .= '});';
$vall .= '';
$vall .= '$("#checkCode2").on("click",function(e){';
$vall .= 'e.preventDefault();';
$vall .= 'function toEnglishNumber(strNum) {';
$vall .= 'var pn = ["۰", "۱", "۲", "۳", "۴", "۵", "۶", "۷", "۸", "۹"];';
$vall .= 'var en = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"];';
$vall .= 'var an = ["٠", "١", "٢", "٣", "٤", "٥", "٦", "٧", "٨", "٩"];';
$vall .= 'var cache = strNum;';
$vall .= 'for (var i = 0; i < 10; i++) {';
$vall .= 'var regex_fa = new RegExp(pn[i], "g");';
$vall .= 'var regex_ar = new RegExp(an[i], "g");';
$vall .= 'cache = cache.replace(regex_fa, en[i]);';
$vall .= 'cache = cache.replace(regex_ar, en[i]);';
$vall .= '}';
$vall .= 'return cache;';
$vall .= '}';
$vall .= 'var phones = toEnglishNumber($("#phoneNumber2").val());';
$vall .= 'var code = toEnglishNumber($("#codeNumber2").val());';
$vall .= '$("#codeNumber2").val("");';
$vall .= 'if(code != ""){';
$vall .= 'jQuery.ajax({';
$vall .= 'type: "post",';
$vall .= 'dataType: "json",';
$vall .= 'data : {phone:phones,verify_code:code},';
$vall .= 'url: "'.esc_attr( get_option('myapiurl') ).'/user/verify/phone",';
$vall .= 'success: function(data){';
$vall .= 'if(data.success == true){';
$vall .= '$("#errorr").hide();';
$vall .= '$("#checkPhoneNumber2").fadeOut();';
$vall .= '$(".successLogin").fadeIn();';
$vall .= 'jQuery.ajax({';
$vall .= 'type: "get",';
$vall .= 'dataType: "json",';
$vall .= 'data : {token:data.data.token},';
$vall .= 'url: "https://avayar.app/wp-content/themes/woodmart/loginpage.php",';
$vall .= 'success: function(data){ } });';
$vall .= '';
 if(isset($_GET["pro"])) {  
$vall .= 'window.location.href = "https://avayar.app/pay/?pro='.$_GET['pro'].'";';
 
  }else{ 
$vall .= 'location.reload();';
  } 
$vall .= '$("#MyaccountLinkLogo").attr("href","/user-account").attr("id","MyaccountLinks");';
$vall .= '$("#logininmyacoount").hide();';
$vall .= '$("#accountPage").show();';
 
$vall .= '}'; 
$vall .= '} ,error: function () {';
$vall .= '$("#errorr").show();';
$vall .= '}'; 
$vall .= '});'; 
$vall .= '}';
$vall .= '});';
 
$vall .= '});';
$vall .= '</script>';
$vall .= '';
$vall .= '';
$vall .= '<div id="logininmyacoount">';
$vall .= '';
$vall .= '';
$vall .= '<form class="applginform" id="getPhoneNumber2">';
$vall .= '<label for="phoneNumber2" class="loginlabel">شماره همراه خود را وارد نمایید</label>';
$vall .= '<input type="text" placeholder="" value="0" style="direction:ltr" name="phone" id="phoneNumber2"  class="loginphone"/>';
$vall .= '<span id="sendPhone2">ثبت</span>';
$vall .= '</form>';
$vall .= '';
$vall .= '';
$vall .= '<form class="applginform" id="checkPhoneNumber2" >';
$vall .= '';
$vall .= '<label for="codeNumber2" class="loginlabel">رمز یکبار مصرف ارسال شده را وارد نمایید</label>';
$vall .= '<span   id="errorr">کد وارد شده صحیح نمی باشد</span>';
$vall .= '<input type="text" placeholder="" name="code" id="codeNumber2"  class="loginphone"/>';
$vall .= '<span id="checkCode2">ثبت</span>';
$vall .= '</form>';
$vall .= '';
$vall .= '<div class="successLogin">';
$vall .= '<svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="user-circle" class="svg-inline--fa fa-user-circle fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 512"><path fill="currentColor" d="M248 8C111 8 0 119 0 256s111 248 248 248 248-111 248-248S385 8 248 8zm0 96c48.6 0 88 39.4 88 88s-39.4 88-88 88-88-39.4-88-88 39.4-88 88-88zm0 344c-58.7 0-111.3-26.6-146.5-68.2 18.8-35.4 55.6-59.8 98.5-59.8 2.4 0 4.8.4 7.1 1.1 13 4.2 26.6 6.9 40.9 6.9 14.3 0 28-2.7 40.9-6.9 2.3-.7 4.7-1.1 7.1-1.1 42.9 0 79.7 24.4 98.5 59.8C359.3 421.4 306.7 448 248 448z"></path></svg>';
$vall .= '<div>به ناحیه کاربری آویار خوش آمدید';
$vall .= '</div>';
$vall .= '';
$vall .= '';
$vall .= '</div>';
$vall .= '</div>';
$vall .= '';
	 return $vall;
?>
<?php }else{ ?>
<?php
$vall = '';
$vall .= '<style>';
$vall .= '';
$vall .= '.containerke {';
$vall .= 'background: #FFFFFF;';
$vall .= 'width: 100%;';
$vall .= 'height: 420px;';
$vall .= 'margin: 0 auto;';
$vall .= 'position: relative;';
$vall .= 'margin-top: 10px;';
$vall .= 'box-shadow: 2px 5px 20px rgb(119 119 119 / 50%);';
$vall .= '}';
$vall .= '';
$vall .= '.CTA {';
$vall .= 'width: 80px;';
$vall .= 'height: 40px;';
$vall .= 'right: -20px;';
$vall .= 'bottom: 0;';
$vall .= 'margin-bottom: 90px;';
$vall .= 'position: absolute;';
$vall .= 'z-index: 1;';
$vall .= 'background: #7ED386;';
$vall .= 'font-size: 1em;';
$vall .= 'transform: rotate(-90deg);';
$vall .= 'transition: all 0.5s ease-in-out;';
$vall .= 'cursor: pointer;';
$vall .= '}';
$vall .= '.CTA h1 {';
$vall .= 'color: #FFFFFF;';
$vall .= 'margin-top: 10px;';
$vall .= 'margin-left: 9px;';
$vall .= '}';
$vall .= '.CTA:hover {';
$vall .= 'background: #3FB6A8;';
$vall .= 'transform: scale(1.1);';
$vall .= '}';
$vall .= '';
$vall .= '.leftbox {';
$vall .= 'float: right;';
$vall .= 'top: -5%;';
$vall .= 'right: 5%;';
$vall .= 'position: absolute;';
$vall .= 'width: 85px;';
$vall .= 'height: 110%;';
$vall .= 'background: #7b013c;';
$vall .= 'box-shadow: 3px 3px 10px rgb(119 119 119 / 50%);';
$vall .= '}';
$vall .= '';
$vall .= '.kenav a {';
$vall .= 'list-style: none;';
$vall .= 'padding: 35px;';
$vall .= 'color: #FFFFFF;';
$vall .= 'font-size: 1.1em;';
$vall .= 'display: block;';
$vall .= 'transition: all 0.3s ease-in-out;';
$vall .= '}';
$vall .= '.kenav a:hover {';
$vall .= 'color: #3FB6A8;';
$vall .= 'transform: scale(1.2);';
$vall .= 'cursor: pointer;';
$vall .= '}';
$vall .= '.kenav a:first-child {';
$vall .= 'margin-top: 100px;';
$vall .= '}';
$vall .= '';
$vall .= '.activeke {';
$vall .= 'color: #3FB6A8;';
$vall .= '}';
$vall .= '';
$vall .= '.rightboxke {';
$vall .= 'float: left;';
$vall .= 'width: 85%;';
$vall .= 'height: 100%;        overflow-y: scroll;padding: 20px 0;';
$vall .= '}';
$vall .= '';
$vall .= '.profile, .payment, .subscription, .privacy, .settingske {';
$vall .= '';
$vall .= 'position: relative;';
$vall .= 'width: 100%;';
$vall .= '}';
$vall .= '';
$vall .= '';
$vall .= '';
$vall .= '';
$vall .= '.btnke {';
$vall .= 'float: right;';
$vall .= 'font-family: "Roboto", sans-serif;';
$vall .= 'text-transform: uppercase;';
$vall .= 'font-size: 10px;';
$vall .= 'border: none;';
$vall .= 'color: #3FB6A8;';
$vall .= '}';
$vall .= '';
$vall .= '.btnke:hover {';
$vall .= 'text-decoration: underline;';
$vall .= 'font-weight: 900;';
$vall .= '}';
$vall .= '';
$vall .= '';
$vall .= '.privacy h2 {';
$vall .= 'margin-top: 25px;';
$vall .= '}';
$vall .= '';
$vall .= '.settingske h2 {';
$vall .= 'margin-top: 25px;';
$vall .= '}';
$vall .= '';
$vall .= '.noshowke {';
$vall .= 'display:none;';
$vall .= '}';
$vall .= '';
$vall .= '@media only screen and (max-width: 800px) 	{';
$vall .= '.leftbox {';
$vall .= 'float: unset;';
$vall .= 'top: -14%;';
$vall .= 'right: 0;';
$vall .= 'position: absolute;';
$vall .= 'width: 100%;';
$vall .= 'height: 50px;';
$vall .= '}.kenav a:first-child {';
$vall .= 'margin-top: 0;}';
$vall .= '.kenav a{';
$vall .= 'list-style: none;';
$vall .= 'padding: 18px;';
$vall .= 'color: #FFFFFF;';
$vall .= 'font-size: 1.1em;';
$vall .= 'display: inline-block;';
$vall .= 'transition: all 0.3s ease-in-out;';
$vall .= 'width: 32%;';
$vall .= 'text-align: center;';
$vall .= '';
$vall .= '}.rightboxke {';
$vall .= 'float: unset;';
$vall .= 'width: 90%;';
$vall .= 'height: 100%;';
$vall .= 'overflow-y: scroll;';
$vall .= 'padding: 20px 0;';
$vall .= 'margin: 0 auto;';
$vall .= '}';
$vall .= '}';
$vall .= '.prodapi {';
$vall .= 'display: inline-block;';
$vall .= 'vertical-align: top;';
$vall .= 'width: 47%;';
$vall .= 'border: 1px dashed #7a7a7a;';
$vall .= 'border-radius: 20px;';
$vall .= 'overflow: hidden;';
$vall .= 'margin: 14px 8px;';
$vall .= '}';
$vall .= '';
$vall .= '.prodapi img {';
$vall .= 'width:100%;';
$vall .= 'display: block;';
$vall .= 'vertical-align: middle;';
$vall .= '}';
$vall .= '';
$vall .= '.prcontents {';
$vall .= 'display: block;';
$vall .= 'vertical-align: middle;';
$vall .= 'padding-right: 10px;';
$vall .= 'padding-left: 10px;';
$vall .= 'text-align: center;';
$vall .= 'padding-top: 6px;';
$vall .= '}';
$vall .= '';
$vall .= '@media only screen and (max-width: 600px) 	{';
$vall .= '';
$vall .= '.prodapi img {width:100%}';
$vall .= '.prodapi {';
$vall .= 'display: block;';
$vall .= '';
$vall .= 'width: 90%;';
$vall .= 'border: 1px dashed #7a7a7a;';
$vall .= 'border-radius: 20px;';
$vall .= 'overflow: hidden;';
$vall .= 'margin: 14px auto;';
$vall .= '}';
$vall .= '}';
$vall .= '</style>';
//$vall .= '<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>';
$vall .= '';
 
$vall .= '<script>';
$vall .= '$(document).ready(function(){';
$vall .= '$("#settingske").on("click",function(){';
$vall .= 'jQuery.ajax({';
$vall .= 'type: "get",';
$vall .= 'dataType:"json",';
$vall .= 'data : {logout:"true"},';
$vall .= 'url: "https://avayar.app/wp-content/themes/woodmart/loginpage.php",';
$vall .= 'success: function(data){ } });';
$vall .= '';
$vall .= 'location.reload();';
$vall .= '});';
$vall .= 'jQuery.ajax({';
$vall .= 'type: "get",';
$vall .= 'dataType: "json",';
$vall .= 'headers: {';
$vall .= '"Authorization":'."'Bearer ' +'".$_SESSION['keshenauth']."'";
$vall .= '},';
$vall .= 'url: "'.esc_attr( get_option('myapiurl') ).'/user/profile",';
$vall .= 'success: function(data){';
$vall .= '';
$vall .= 'var allproducts = data.data.products;';
$vall .= '';
$vall .= '$.each(allproducts, function( index, value ) {';
	 
$vall .= 'var pricc = value.price+""; pricc =  pricc.slice(0, -1);';
$vall .= '$(".myprr").append("<div class='."'prodapi'".'><div class='."'fixdis'".'><img src='."'+value.image+'".' /><div class='."'prcontents'".'><h3>"+value.name+"</h3><span><b>قیمت : </b>"+pricc+" تومان</span></div></div></div>");';
$vall .= '});';
$vall .= '';
$vall .= 'if(data.data.profile.name == "0"){';
$vall .= '$(".app_yournames").html("ثبت نشده");';
$vall .= '';
$vall .= '}else{';
$vall .= '$(".app_yournames").html(data.data.profile.name);';
$vall .= '}';
$vall .= '$(".app_yourphones").html(data.data.profile.phone);';
$vall .= '';
$vall .= '}';
$vall .= '';
$vall .= '});'; 
 
$vall .= '$(".kenav a").click(function(e) {';
$vall .= 'e.preventDefault();';
$vall .= '$(".kenav a").removeClass("activeke");';
$vall .= '$(this).addClass("activeke");';
$vall .= 'if(this.id === !"payment"){';
$vall .= '$(".payment").addClass("noshowke");';
$vall .= '}';
$vall .= 'else if(this.id === "payment") {';
$vall .= '$(".payment").removeClass("noshowke");';
$vall .= '$(".rightboxke").children().not(".payment").addClass("noshowke");';
$vall .= '}';
$vall .= 'else if (this.id === "profile") {';
$vall .= '$(".profile").removeClass("noshowke");';
$vall .= '$(".rightboxke").children().not(".profile").addClass("noshowke");';
$vall .= '}';
$vall .= 'else if(this.id === "subscription") {';
$vall .= '$(".subscription").removeClass("noshowke");';
$vall .= '$(".rightboxke").children().not(".subscription").addClass("noshowke");';
$vall .= '}';
$vall .= 'else if(this.id === "privacy") {';
$vall .= '$(".privacy").removeClass("noshowke");';
$vall .= '$(".rightboxke").children().not(".privacy").addClass("noshowke");';
$vall .= '}';
$vall .= 'else if(this.id === "settingske") {';
$vall .= '$(".settingske").removeClass("noshowke");';
$vall .= '$(".rightboxke").children().not(".settingske").addClass("noshowke");';
$vall .= '}';
$vall .= '});    });';
$vall .= '</script>';
 
$vall .= '<div class="containerke">';
$vall .= '';
$vall .= '<div class="leftbox">';
$vall .= '<nav class="kenav">';
$vall .= '<a id="profile" class="activeke"><i class="fa fa-user"></i></a>';
$vall .= '<a id="payment"><i class="fa fa-shopping-cart"></i></a>';
$vall .= '';
$vall .= '<a id="settingske"><i class="fa fa-sign-out-alt"></i></a>';
$vall .= '';
$vall .= '</nav>';
$vall .= '</div>';
$vall .= '<div class="rightboxke">';
$vall .= '<div class="profile">';
$vall .= '<h1>اطلاعات کاربر</h1>';
$vall .= '<h2>نام</h2>';
$vall .= '<p style=" font-size: 18px;" class="app_yournames"></p>';
$vall .= '<h2>شماره تماس</h2>';
$vall .= '<p style=" font-size: 18px;" class="app_yourphones"> </p>';
$vall .= '';
$vall .= '</div>';
$vall .= '';
$vall .= '<div class="payment noshowke">';
$vall .= '<h1>محصولات خریداری شده</h1>';
$vall .= '<div class="myprr">';
$vall .= '';
$vall .= '</div>';
$vall .= '</div>';
$vall .= '';
$vall .= '';
$vall .= '';
$vall .= '</div>';
$vall .= '</div>';
return $vall;
 
 }
 }
 
 add_shortcode( 'user-account' , 'accountFrm' );
 function bt(){
return "";
}
 
   add_shortcode( 'bt' , 'bt' );
 

 function pay(){
	 if(isset($_GET["pro"])){
		  
$vall = "";
$vall .= '<style>';
$vall .= '.loader {';
$vall .= 'width: 350px;';
$vall .= 'height: 90px;';
$vall .= 'line-height: 90px;';
$vall .= 'text-align: center;';
$vall .= 'position: absolute;';
$vall .= 'top: 50%;';
$vall .= 'left: 50%;';
$vall .= 'transform: translate(-50%, -50%);';
$vall .= 'font-weight: 900;';
$vall .= 'color: #ce4233;';
$vall .= 'letter-spacing: 0;';
$vall .= 'font-size: 26px;';
$vall .= '}';
$vall .= '.loader::before, .loader::after {';
$vall .= 'content: "";';
$vall .= 'display: block;';
$vall .= 'width: 15px;';
$vall .= 'height: 15px;';
$vall .= 'background: #ce4233;';
$vall .= 'position: absolute;';
$vall .= '-webkit-animation: load 0.7s infinite alternate ease-in-out;';
$vall .= 'animation: load 0.7s infinite alternate ease-in-out;';
$vall .= '}';
$vall .= '.loader::before {';
$vall .= 'top: 0;';
$vall .= '}';
$vall .= '.loader::after {';
$vall .= 'bottom: 0;';
$vall .= '}';
$vall .= '';
$vall .= '@-webkit-keyframes load {';
$vall .= '0% {';
$vall .= 'left: 0;';
$vall .= 'height: 30px;';
$vall .= 'width: 15px;';
$vall .= '}';
$vall .= '50% {';
$vall .= 'height: 8px;';
$vall .= 'width: 40px;';
$vall .= '}';
$vall .= '100% {';
$vall .= 'left:335px;';
$vall .= 'height: 30px;';
$vall .= 'width: 15px;';
$vall .= '}';
$vall .= '}';
$vall .= '';
$vall .= '@keyframes load {';
$vall .= '0% {';
$vall .= 'left: 0;';
$vall .= 'height: 30px;';
$vall .= 'width: 15px;';
$vall .= '}';
$vall .= '50% {';
$vall .= 'height: 8px;';
$vall .= 'width: 40px;';
$vall .= '}';
$vall .= '100% {';
$vall .= 'left: 335px;';
$vall .= 'height: 30px;';
$vall .= 'width: 15px;';
$vall .= '}';
$vall .= '}.success-message {';
$vall .= 'text-align: center;';
$vall .= 'max-width: 500px;';
$vall .= 'position: absolute;';
$vall .= 'top: 50%;';
$vall .= 'left: 50%;';
$vall .= 'transform: translate(-50%, -50%);';
$vall .= '}';
$vall .= '';
$vall .= '.success-message__icon {';
$vall .= 'max-width: 75px;';
$vall .= '}';
$vall .= '';
$vall .= '.success-message__title {';
$vall .= 'color: #3DC480;';
$vall .= 'transition: all 200ms ease;';
$vall .= '}';
$vall .= '.active .success-message__title {';
$vall .= 'transform: translateY(0);';
$vall .= 'opacity: 1;';
$vall .= '}';
$vall .= '';
$vall .= '.success-message__content {';
$vall .= 'color: #B8BABB;';
$vall .= 'transform: translateY(0);';
$vall .= '';
$vall .= 'transition: all 200ms ease;';
$vall .= 'transition-delay: 50ms;';
$vall .= '}';
$vall .= '.active .success-message__content {';
$vall .= 'transform: translateY(0);';
$vall .= 'opacity: 1;';
$vall .= '}';
$vall .= '';
$vall .= '.icon-checkmark circle {';
$vall .= 'fill: #3DC480;';
$vall .= 'transform-origin: 50% 50%;';
$vall .= '';
$vall .= 'transition: transform 200ms cubic-bezier(0.22, 0.96, 0.38, 0.98);';
$vall .= '}';
$vall .= '.icon-checkmark path {';
$vall .= 'transition: stroke-dashoffset 350ms ease;';
$vall .= 'transition-delay: 100ms;';
$vall .= '}';
$vall .= '.active .icon-checkmark circle {';
$vall .= 'transform: scale(1);';
$vall .= '}.unsuccess-message .success-message__title {';
$vall .= 'color: #ff3e3e;';
$vall .= 'transition: all 200ms ease;';
$vall .= '}svg.svg-inline--fa.fa-times.fa-w-11 {';
$vall .= 'width: 65px;';
$vall .= 'height: 65px;';
$vall .= 'color: #FFF;';
$vall .= 'background: #ff3e3e;';
$vall .= 'padding: 7px;';
$vall .= 'border-radius: 50%;';
$vall .= '}';
$vall .= '';
$vall .= '.unsuccess-message {';
$vall .= 'text-align: center;';
$vall .= '}.success-message__content a {';
$vall .= 'background: #7b013c;';
$vall .= 'border-radius: 5px;';
$vall .= 'padding: 6px 40px;';
$vall .= 'color: #FFF;';
$vall .= 'font-size: 19px;';
$vall .= '}';
$vall .= '.success-message,.unsuccess-message{';
$vall .= 'display:none;';
$vall .= '}';
$vall .= '</style>';
$vall .= '<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>';
$vall .= '<script>';
$vall .= '$(document).ready(function(){';
$vall .= 'jQuery.ajax({';
$vall .= 'type: "post",'; 
$vall .= 'data : {productId:"'.$_GET['pro'].'",currency:"irr",source:"site"},';
$vall .= 'dataType: "json",';
$vall .= 'headers: {';
$vall .= '"Authorization":'."'Bearer ' +".'"'.$_SESSION['keshenauth'].'"';
$vall .= '},';
$vall .= 'url: "'.esc_attr( get_option('myapiurl') ).'/product/buy",';
$vall .= 'success: function(data){';
$vall .= 'if(data.success == true){';
$vall .= 'window.location.href = data.data.link;';
$vall .= '}else{';
$vall .= '$(".success-message").show();';
$vall .= '$(".loader").hide();';
$vall .= '}';
$vall .= '';
$vall .= '}';
$vall .= '';
$vall .= '});	});';
$vall .= '</script>';
 
$vall .= '';
$vall .= '<div class="success-message" >';
$vall .= '<svg viewBox="0 0 76 76" class="success-message__icon icon-checkmark">';
$vall .= '<circle cx="38" cy="38" r="36"/>';
$vall .= '<path fill="none" stroke="#FFFFFF" stroke-width="5" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" d="M17.7,40.9l10.9,10.9l28.7-28.7"/>';
$vall .= '</svg>';
$vall .= '<h1 class="success-message__title">محصول قبلا خریداری شده است</h1>';
$vall .= '<div class="success-message__content">';
$vall .= '<p>برای استفاده از محصول وارد حساب کاربری خود در اپلیکیشن شوید</p>';
$vall .= '<a href="https://avatour.app/?utm_source=thank_you_page&utm_medium=internal&utm_campaign=insider/" id="aOpenApp">باز کردن اپلیکیشن</a>';
$vall .= '</div>';
$vall .= '</div>';
$vall .= '';
$vall .= '<div class="loader">در حال انتقال به درگاه پرداخت</div>';
 
 } return $vall;
	 }
  add_shortcode( 'pay' , 'pay' );

 function thank(){
 $vall = '';
//$vall .= '<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>';
$vall .= '<script>';
$vall .= '$(document).ready(function(){';
$vall .= 'jQuery.ajax({';
$vall .= 'type: "get",';
$vall .= '';
$vall .= 'dataType: "json",';
$vall .= 'headers: {';
$vall .= '"Authorization":'."'Bearer ' +".'"'.$_SESSION['keshenauth'].'"';
$vall .= '},';
$vall .= 'url: "'.esc_attr( get_option('myapiurl') ).'/payment/order_id/'.$_GET['orderId'].'",';
$vall .= 'success: function(data){';
$vall .= 'var paid = parseInt(data.data.paid);';
$vall .= 'var amount = parseInt(data.data.amount);';
$vall .= 'if(paid < amount){';
$vall .= '$(".success-message").hide();';
$vall .= '$(".unsuccess-message").show();';
$vall .= '';
$vall .= '';
$vall .= '}else{';
$vall .= '$(".success-message").show();';
$vall .= '$(".unsuccess-message").hide();';
$vall .= '}';
$vall .= '}';
$vall .= '';
$vall .= '});	});';
$vall .= '</script>';
$vall .= '<style>';
$vall .= '.success-message {';
$vall .= 'text-align: center;';
$vall .= 'max-width: 500px;';
$vall .= 'position: absolute;';
$vall .= 'top: 50%;';
$vall .= 'left: 50%;';
$vall .= 'transform: translate(-50%, -50%);';
$vall .= '}';
$vall .= '';
$vall .= '.success-message__icon {';
$vall .= 'max-width: 75px;';
$vall .= '}';
$vall .= '';
$vall .= '.success-message__title {';
$vall .= 'color: #3DC480;';
$vall .= 'transition: all 200ms ease;';
$vall .= '}';
$vall .= '.active .success-message__title {';
$vall .= 'transform: translateY(0);';
$vall .= 'opacity: 1;';
$vall .= '}';
$vall .= '';
$vall .= '.success-message__content {';
$vall .= 'color: #B8BABB;';
$vall .= 'transform: translateY(0);';
$vall .= '';
$vall .= 'transition: all 200ms ease;';
$vall .= 'transition-delay: 50ms;';
$vall .= '}';
$vall .= '.active .success-message__content {';
$vall .= 'transform: translateY(0);';
$vall .= 'opacity: 1;';
$vall .= '}';
$vall .= '';
$vall .= '.icon-checkmark circle {';
$vall .= 'fill: #3DC480;';
$vall .= 'transform-origin: 50% 50%;';
$vall .= '';
$vall .= 'transition: transform 200ms cubic-bezier(0.22, 0.96, 0.38, 0.98);';
$vall .= '}';
$vall .= '.icon-checkmark path {';
$vall .= 'transition: stroke-dashoffset 350ms ease;';
$vall .= 'transition-delay: 100ms;';
$vall .= '}';
$vall .= '.active .icon-checkmark circle {';
$vall .= 'transform: scale(1);';
$vall .= '}.unsuccess-message .success-message__title {';
$vall .= 'color: #ff3e3e;';
$vall .= 'transition: all 200ms ease;';
$vall .= '}svg.svg-inline--fa.fa-times.fa-w-11 {';
$vall .= 'width: 65px;';
$vall .= 'height: 65px;';
$vall .= 'color: #FFF;';
$vall .= 'background: #ff3e3e;';
$vall .= 'padding: 7px;';
$vall .= 'border-radius: 50%;';
$vall .= '}';
$vall .= '';
$vall .= '.unsuccess-message {';
$vall .= 'text-align: center;';
$vall .= '}.success-message__content a {';
$vall .= 'background: #7b013c;';
$vall .= 'border-radius: 5px;';
$vall .= 'padding: 6px 40px;';
$vall .= 'color: #FFF;';
$vall .= 'font-size: 19px;';
$vall .= '}';
$vall .= '.success-message,.unsuccess-message{';
$vall .= 'display:none;';
$vall .= '}';
$vall .= '</style>';
$vall .= '';
$vall .= '<div class="success-message" >';
$vall .= '<svg viewBox="0 0 76 76" class="success-message__icon icon-checkmark">';
$vall .= '<circle cx="38" cy="38" r="36"/>';
$vall .= '<path fill="none" stroke="#FFFFFF" stroke-width="5" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" d="M17.7,40.9l10.9,10.9l28.7-28.7"/>';
$vall .= '</svg>';
$vall .= '<h1 class="success-message__title">با موفقیت انجام شد</h1>';
$vall .= '<div class="success-message__content">';
$vall .= '<p>برای استفاده از محصول وارد حساب کاربری خود در اپلیکیشن شوید</p>';
$vall .= '<a href="https://avatour.app/?utm_source=thank_you_page&utm_medium=internal&utm_campaign=insider#/" id="aOpenApp">باز کردن اپلیکیشن</a>';
$vall .= '</div>';
$vall .= '</div>';
$vall .= '';
$vall .= '';
$vall .= '<div class="unsuccess-message">';
$vall .= '<svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="times" class="svg-inline--fa fa-times fa-w-11" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 352 512"><path fill="currentColor" d="M242.72 256l100.07-100.07c12.28-12.28 12.28-32.19 0-44.48l-22.24-22.24c-12.28-12.28-32.19-12.28-44.48 0L176 189.28 75.93 89.21c-12.28-12.28-32.19-12.28-44.48 0L9.21 111.45c-12.28 12.28-12.28 32.19 0 44.48L109.28 256 9.21 356.07c-12.28 12.28-12.28 32.19 0 44.48l22.24 22.24c12.28 12.28 32.2 12.28 44.48 0L176 322.72l100.07 100.07c12.28 12.28 32.2 12.28 44.48 0l22.24-22.24c12.28-12.28 12.28-32.19 0-44.48L242.72 256z"></path></svg>';
$vall .= '<h1 class="success-message__title">متاسفیم ، خرید شما نا موفق بود</h1>';
$vall .= '<div class="success-message__content">';
$vall .= '<p>خرید شما ناموفق بود لطفا دوباره تلاش فرمایید</p>';
$vall .= '<a href="/shop/">رفتن به فروشگاه</a>';
$vall .= '</div>';
$vall .= '</div>';
$vall .= '';
	 return $vall;
?>

<?php
 
	 	 }
  add_shortcode( 'thank' , 'thank' );


add_action('admin_menu', 'wooAdminMenu');
 function wooAdminMenu() {
   add_menu_page('d', 'تنظیمات api ', 'administrator', 'WooSetting', 'WooSetting_page', 'dashicons-admin-generic');
 }


 function WooSetting_page() { 
 
 echo '<br /><br />';
 echo '<form method="post" action="options.php">';
 settings_fields( 'WooSetting-group' ); 
  do_settings_sections( 'WooSetting-group' );  
	
	  echo '<label class="KnWooLabel" >آدرس اصلی api خود را وارد نمایید</label>';
    echo '<input class="KnWooInput"  type="text" name="myapiurl" value="'.esc_attr( get_option('myapiurl') ).'" />';

     submit_button(); 

   echo '</form>';

     }

add_action( 'admin_init', 'WooSetting' );

function WooSetting() {
  register_setting( 'WooSetting-group', 'myapiurl' );
}
 